### ISSUE TITLE
compatibility with react 18

### ISSUE THREAD

**Issue by jakeFeldman** [auth0/auth0-spa-js#850] opened 2021-12-15 03:31 UTC
### Describe the problem

I recently upgraded to the beta version react 18 and I started encountering an `Invalid authorization code` error. The function calls for `getUser` and `getTokenSilently` resolve and I receive a token. 

The POST back to `https://<domain>.auth0.com/oauth/token` fails with a 403 

Thanks in advance and let me know if more info is needed

```
POST https://<domain>.us.auth0.com/oauth/token 403
Error: Invalid authorization code
    at new n (errors.ts:11)
    at http.ts:148
    at tslib.es6.js:102
    at Object.next (tslib.es6.js:83)
    at a (tslib.es6.js:73)
```

### What was the expected behavior?

POST back to authz the client correctly

### Reproduction

see reproduction repo (https://github.com/jakeFeldman/auth0-react-18-compat-issue)

1. yarn install
2. copy sample.env and add required auth0 keys for test tenant
3. yarn start
4. look at index.js
5. current setup is using ReactDOM.render method (react 17 and below)
```tsx
// WORKS AS EXPECTED (i.e. React <= 17)
ReactDOM.render(
  <React.StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </React.StrictMode>,
  document.getElementById('root')
);
```

6. Comment out ReactDOM.render block and uncomment ReactDOM.createRoot block
```tsx
const root = ReactDOM.createRoot(document.getElementById('root'))

root.render(
  <React.StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </React.StrictMode>
);
```
7. Refresh and see the error
```
POST https://<domain>.us.auth0.com/oauth/token 403
Error: Invalid authorization code
    at new n (errors.ts:11)
    at http.ts:148
    at tslib.es6.js:102
    at Object.next (tslib.es6.js:83)
    at a (tslib.es6.js:73)
```
**Can the behavior be reproduced using the [SPA SDK Playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground)?**  No, seems to be react specific

### Environment

- **Version of `auth0-spa-js` used:** 1.19.3
- **Which browsers have you tested in?** Chrome, Firefox
- **Which framework are you using, if applicable (Angular, React, etc):** React
- **Other modules/plugins/libraries that might be involved:** react, react-dom

**Comment by stevehobbsdev** [comment] 2021-12-15 09:52
Thanks for the report. Typically we don't dive too deeply into issues with beta software, but I'll have a look at the repro you've kindly provided and see if I can see anything (thanks for that!)

**Comment by stevehobbsdev** [comment] 2021-12-15 10:56
I can see the issue occuring. The error is happening because `handleRedirectCallback` is being called twice - it fails on the second time because the code has already been exchanged (you can see these two transactions happening in the network log). If I reinstate the old code that works, `handleRedirectCallback` is only called once.

So something about the component render code or the clearing of the URL path isn't working as intended here, as `handleRedirectCallback` should only be called once.

Closing this for now as I don't believe it's an issue with the SDK, but happy to continue the conversation. Hopefully the above gives you something to go on.

**Closed by stevehobbsdev** 2021-12-15 10:56 UTC
Labels: bug report

**Comment by jakeFeldman** [comment] 2021-12-15 18:08
@stevehobbsdev Thank you for taking a look at this. That makes sense. I believe React.StrictMode renders components twice (i.e. calls useEffect twice). Thanks for identifying that `handleRedirectCallback` should only be called once. This makes sense!
