### ISSUE TITLE
Login options ui_locales ignored by Universal Login

### ISSUE THREAD

**Issue by bgever** [auth0/auth0-spa-js#305] opened 2019-12-13 06:20 UTC
### Description

When I set the `ui_locales` property of the login options, the Universal Login page does not reflect the provided language or languages.

> The space-separated list of language tags, ordered by preference.
> For example: `'fr-CA fr en'`.
https://github.com/auth0/auth0-spa-js/blob/902062723784d29b1bbeac9ba634071a51e38c4b/src/global.ts#L29

I can see that the `ui_locales` query string parameter is passed to the lock screen, but the lock.js script doesn't process the parameter.

### Reproduction

1. Activate additional languages in the Auth0 tenant settings.
2. Set the `ui_locales` property with the call to `loginWithRedirect()`.
3. Follow the login and on the Universal Login page note that the language isn't reflected.

### Environment

- **Version of this library used:** 1.6.0
- **Version of the platform or framework used, if applicable:** Angular 8.2.14
- **Other relevant versions (language, server software, OS, browser):** macOS 10.15.1, Chrome 78
- **Other modules/plugins/libraries that might be involved:** RXJS

Related support ticket: 443466

**Comment by stevehobbsdev** [comment] 2019-12-19 15:22
Can I ask - are you using the classic or the new Universal Login experience?

**Comment by bgever** [comment] 2019-12-31 15:10
The Universal Login experience, with a customized base template.

**Comment by bgever** [comment] 2020-01-09 04:30
@stevehobbsdev to be clear, it's the Classic version of the Universal Login.

**Comment by stevehobbsdev** [comment] 2020-01-10 10:19
@bgever I've initiated a discussion internally about this, let me get back to you.

**Comment by stevehobbsdev** [comment] 2020-01-10 12:06
@bgever I've had it confirmed that the classic Lock experience doesn't support automatically switching the locale on your behalf. If you're using a custom template for Lock, you can modify the template so that it picks up the `ui_locales` parameter and the configures Lock using the `language` option, but it won't do this automatically.

The new Universal Login experience _does_ support switching the locale in the manner you describe, but must be one of the supported languages and must be turned on for your tenant. See [this article](https://auth0.com/docs/universal-login/i18n) for more information on how to do that.

Closing this for now as it's not really an issue with this SDK, but if you have anything further, please feel free to continue the discussion or raise a topic on our [community forums](https://community.auth0.com).

**Closed** 2020-01-10 12:06 UTC

**Comment by bgever** [comment] 2020-01-17 10:08
Ok, now I understand it's because of the difference between the Classic and New versions of the Universal Login.

Thanks for looking into the matter, and also thanks for the Auth0 support team to already suggest the `language` option workaround for the Classic version which is working for us.

**Comment by dsebastien** [comment] 2021-03-08 11:37
I had the same issue. I'm using the Universal Login, with a customized login page.

I solved it by  adding this to my login page:

```
if(config.extraParams && config.extraParams.ui_locales) {
  language = config.extraParams.ui_locales;
}
```

**Comment by edolganov** [comment] 2021-08-19 12:17
> I had the same issue. I'm using the Universal Login, with a customized login page.
> 
> I solved it by adding this to my login page:
> 
> ```
> if(config.extraParams && config.extraParams.ui_locales) {
>   language = config.extraParams.ui_locales;
> }
> ```

It works for me! Thanks!

**Comment by som-matrix** [comment] 2023-04-24 03:27
Hey folks i am using New universal login experience, and using the `loginWithRedirect` method for login, so how do I pass `ui_locales` from here?

**Comment by frederikprijck** [comment] 2023-04-24 09:44
You can send it by setting `authorizationParams.ui_locales` when calling `login`, see https://github.com/auth0/auth0-spa-js/blob/master/src/global.ts#L31.

**Comment by som-matrix** [comment] 2023-04-25 09:24
Hey folks , as i am using `loginWithRedirect` , after successful authentication from the login page , how can I return back to the route from where I clicked login ?
For eg: if i am in route `/explore` and i clicked `Login using Auth0` i will be redirected to auth0 login page and after successful authentication i want to return to `/explore` again

**Comment by frederikprijck** [comment] 2023-04-25 09:40
You can use `appState.target` on `loginWithRedirect`, but please do not use closed issues for random questions.

**Comment by som-matrix** [comment] 2023-04-25 10:05
> You can use `appState.target` on `loginWithRedirect`, but please do not use closed issues for questions like this.

Sorry my bad , thanks for the solution.
