### ISSUE TITLE
Unreliable token refreshing on Safari with multiple tabs

### ISSUE THREAD

**Issue by mbuczko** [auth0/auth0-spa-js#755] opened 2021-06-21 15:24 UTC
With the recent Safari Version 14.1 (16611.1.21.161.3) (macOS Big Sur) we observe weird behaviour when token is being refreshed in one tab and read afterwards from the LocalStorage in the other tab. Surprisingly, token in the 2nd tab remains the same as if no refreshing happened.

Going down and investigating the problem we came to the conclusion that we are beaten by this bug https://bugs.webkit.org/show_bug.cgi?id=225344. Although it's not on your side, I'm curious if you have also experienced this issue and if so, is there anything you could suggest to get around the problem or minimize the impact?

Seems like the only viable solution for now would be to disallow the app being run on multiple tabs on Safari (at least till the fix gets rolled out) but that's a bit drastic, last line of defence.

**Comment by adamjmcgrath** [comment] 2021-06-21 16:35
Hi @mbuczko - thanks for raising this

>  I'm curious if you have also experienced this issue

Yep - I'm able to reproduce your issue on the playground app in Safari Version 14.1 (16611.1.21.161.3) (macOS Big Sur) 

> is there anything you could suggest to get around the problem or minimize the impact?

If you're using [Custom domains](https://auth0.com/docs/authorization/renew-tokens-when-using-safari#workarounds), which we recommend for production, then `getTokenSilently` should fallback to the `web_message` flow which should still work

**Comment by smogg** [comment] 2021-06-25 19:57
@adamjmcgrath can you elaborate a bit more on the `web_message` fallback? What happens in case of Refresh Token Rotation - wouldn't the scenario mean that multiple tabs will try to use the same refresh-token to obtain a new AT, which would in turn cause the entire family of tokens to be revoked?

**Comment by stevehobbsdev** [comment] 2021-07-05 09:24
@smogg If you're hitting that scenario, you should be able to use a leeway value so that if multiple tabs try to use the old token within that leeway, the token should still be exchanged. See the [Reuse Interval](https://auth0.com/docs/tokens/refresh-tokens/configure-refresh-token-rotation#configure-in-the-dashboard) setting when configuring refresh token rotation.

**Comment by smogg** [comment] 2021-07-05 12:59
@stevehobbsdev that setting also allows an attacker to reuse the token, which lessens the security of our system because of a bug in a single browser. I'd rather not change it for that reason. 
Just so I understand correctly - the `web_message` fallback is not something that will happen in case of using Refresh Token Rotation?

**Comment by stevehobbsdev** [comment] 2021-07-05 21:22
Sure, just wanted to point it out as an option that is designed to resolve this specific question around concurrency, given that the size of leeway we're talking about will usually be very small (a few seconds), and only applies to the current and previous refresh token, not all refresh tokens.

> the web_message fallback is not something that will happen in case of using Refresh Token Rotation?

Yes, it will happen in the case of using Refresh Token Rotation. If for example you have no refresh token to use, or the call to exchange the refresh token for another access token fails, then the SDK will attempt to use `web_message` in a hidden iframe as a fallback to try and get another token. This could in turn fail if it's being run in a browser where third-party cookies are blocked, in which case the only option is to put the user back through an interactive login flow by calling `loginWithRedirect` or `loginWithPopup`.

**Comment by stevehobbsdev** [comment] 2021-07-23 11:40
Closing as the original question looks to be answerd. If there's anything additional we can do to help, please feel free to continue the conversation or open a fresh issue.

**Closed by stevehobbsdev** 2021-07-23 11:40 UTC
Labels: needs investigation
