### ISSUE TITLE
QuotaExceededError thrown from getTokenSilently()

### ISSUE THREAD

**Issue by roaks3** [auth0/auth0-spa-js#455] opened 2020-05-07 20:37 UTC
### Description

It is possible for the `getTokenSilently()` function to throw a `QuotaExceededError` when attempting to acquire a lock. This is because `localStorage.setItem()` is called in the `browser-tabs-lock` library [here](https://github.com/supertokens/browser-tabs-lock/blob/master/index.ts#L99), and if this call fails, an error is thrown all the way up through the stack. This can effectively blocks an end-user from silently logging in.

The expected behavior was that if `localStorage` is unavailable for any reason, `getTokenSilently()` would be able to proceed without using a lock, and a user could still silently login.

### Reproduction

1. Fill `localStorage` using the Console on a page which calls `getTokenSilently()`. Something like [this](https://stackoverflow.com/questions/45760110/how-to-fill-javascript-localstorage-to-its-max-capacity-quickly) worked for us
2. Trigger `getTokenSilently()`. For our application, it is called on load, so you can just refresh the tab
3. A `QuotaExceededError` is thrown, and the token is never requested

### Environment

- **Version of this library used:** 1.6.4
- **Other relevant versions (language, server software, OS, browser):** OSX Firefox
- **Other modules/plugins/libraries that might be involved:** [browser-tabs-lock](https://github.com/supertokens/browser-tabs-lock)

**Comment by stevehobbsdev** [comment] 2020-05-10 21:23
@roaks3 Thanks for raising. Continuing to do silent login in the event that the browser lock fails could have unintended consequences, for you or for others - the reason we have the lock in place is so that multiple requests to the token endpoint would yield tokens in the right order.

Other than manually filling up local storage, are you encountering scenarios that is causing local storage to fill up local storage because of something this SDK is doing, or are there other factors involved?

**Comment by roaks3** [comment] 2020-05-14 18:15
@stevehobbsdev this has actually been very hard for us to gain insight into. We see the error being logged in the browser for a number of our users (through Bugsnag), but so far we don't have much information beyond that. We intend to track the size of local storage at the time of this error, but we're unsure how much that will tell us.

So far, we have no reason to believe that the QuotaExceededError is caused by something that this SDK is doing wrong. Our intent with bringing this issue up is more around the handling of this error, where the user would ideally still be able to silently authenticate.

**Comment by stevehobbsdev** [comment] 2020-06-17 11:01
We'll close this issue for now, thanks for raising it. We cannot remove the browser lock functionality as it is at the moment but have taken the feedback on board to see how we can improve this experience in the future.

**Closed by stevehobbsdev** 2020-06-17 11:01 UTC

**Comment by frsc** [comment] 2020-09-14 13:43
Hi! We are currently experience this issue with a few of our customers (using the Edge browser). @roaks3 Did you guys figure something out?

**Comment by stevehobbsdev** [comment] 2020-09-14 16:30
@frsc Can you let me know which version of the SDK you're using? Has this just happened recently (i.e. after an update)?

**Comment by buren** [comment] 2020-09-14 18:38
@stevehobbsdev also experiencing this issue with Lock v11.20. Customer had the issue on Edge (confirmed over screen share) and claimed to have the same issue on Chrome (not confirmed, but believable).

**Comment by frsc** [comment] 2020-09-15 06:13
@stevehobbsdev We are using version 1.11.0 of auth0/auth0-spa-js, updated quite recently (~ one month ago). This issue fist occurred a few days ago for a newly signed up user using Edge.

**Comment by stevehobbsdev** [comment] 2020-09-16 08:49
@frsc Thanks. I was just asking because 1.12.0 introduces session storage when working with transactions, but I can rule that out.

We do use a library that uses local storage to effect a "lock" between tabs so that we can serialize requests to the token endpoint, but so far we've been unable to reproduce the issue here, so I feel like this is environmental rather than an issue with the library. However, if you have a small sample you can share which reliably reproduces the problem, I'll be more than happy to take a look.
