### ISSUE TITLE
Invalid state on loginWithPopup on Chrome

### ISSUE THREAD

**Issue by alexvdvalk** [auth0/auth0-spa-js#582] opened 2020-09-20 12:17 UTC
### Describe the problem

> If popup is closed before a user signs in, and is then reoppend, an "Invalid State" error is thrown. 

### What was the expected behavior?

> A new state should be generated on each loginWithPopup() call.

### Reproduction

- configure auth0 client
- click button to launch auth0.loginWithPopup(). No parameters are provided to the loginWithPopup function
- open dev tools
- Note the 'state' query parameter in the popup URL
- manually close popup before logging in, with the browser close button
- Open the loginWithPopup again
- Note that a new 'state' query parameter is generated
- Enter valid credentials and submit
- Note the "Invalid State" error is logged to the console.
- App functions as normal after this.

### Environment

- auth0-spa-js version: 1.12.1
- Browser: Chrome 85
- Framework: Svelte 3 and Angular 10.

Also noted: During testing, the timeout error was also thrown, but this did not seem to affect the functioning of the application.

**Comment by alexvdvalk** [comment] 2020-09-20 14:01
Confirmed that this is also occurring when using the Auth0 SPA JS Playground, Login Popup option.

**Comment by stevehobbsdev** [comment] 2020-09-22 14:41
Thanks for raising, I've confirmed that I'm seeing what you're reporting.

Despite the error in the console, does everything work normally for you or does it block you in some way?

**Comment by alexvdvalk** [comment] 2020-09-22 14:44
It's works normally afterward, and it's the same with the timeout. The default timeout is 60 sec, and if I leave the popup open for a while and then login, I get the timeout error, but the login is still successful.

**Comment by stevehobbsdev** [comment] 2020-09-23 10:05
Ok, it kind of makes sense. Looks like popup is resolving an older message which is no longer valid as it has the wrong state (the state is generated on every invocation of the popup) but otherwise continue to work.

As it's not blocking functionality of the SDK, I've taken a note internally to see what we can do to improve the experience here. Thanks for the report 👍

**Closed by stevehobbsdev** 2020-09-23 10:05 UTC
Labels: bug report
