### ISSUE TITLE
TypeError: ns.GetCommandSrc is not a function

### ISSUE THREAD

**Issue by Nadya913** [auth0/auth0-spa-js#299] opened 2019-12-04 05:41 UTC
### Description

User can't log in and the type error 'TypeError: ns.GetCommandSrc is not a function' appears in the console in Win10 and Chrome 

TypeError: ns.GetCommandSrc is not a function
    at GetCommandUrl (main.js?attr=QWX0Jz7yAumcdK241DhVh8-ke2iaPx_ztEo955ADd-pkoR5h5E5xxm5HGv7vi4iTYPY1ljCdE447zdWuyNjEPpwqbJPT8uwj6OCfwHnH9FKhvxt6LPIkWrZJ57eF-XhAXojMYPtACHfip4soT_EwOp5KEeYWbO-nH38Jn3GzHpQTS5O3fGwX3S1e9oK8aqJgGo0PKDsupfIIM-qQJgs-xg:988)
    at XMLHttpRequest.window.XMLHttpRequest.open (main.js?attr=QWX0Jz7yAumcdK241DhVh8-ke2iaPx_ztEo955ADd-pkoR5h5E5xxm5HGv7vi4iTYPY1ljCdE447zdWuyNjEPpwqbJPT8uwj6OCfwHnH9FKhvxt6LPIkWrZJ57eF-XhAXojMYPtACHfip4soT_EwOp5KEeYWbO-nH38Jn3GzHpQTS5O3fGwX3S1e9oK8aqJgGo0PKDsupfIIM-qQJgs-xg:1023)
    at auth0-spa-js.production.js:1171
    at new Promise (<anonymous>)
    at xn (auth0-spa-js.production.js:1133)
    at auth0-spa-js.production.js:1346
    at auth0-spa-js.production.js:152
    at Object.next (auth0-spa-js.production.js:100)
    at auth0-spa-js.production.js:72
    at new Promise (<anonymous>)

### Environment
"@auth0/auth0-spa-js": "^1.2.3"
Chrome 78.0.3904.108 on Windows 10 Pro

**Comment by stevehobbsdev** [comment] 2019-12-04 10:07
@Nadya913 We're unable to reproduce this here - could you please provide a small repro that we can use to evaluate the problem?

**Comment by paulfalgout** [comment] 2019-12-04 12:08
I really don't think this is related https://github.com/search?l=JavaScript&p=1&q=GetCommandSrc&type=Code

**Comment by stevehobbsdev** [comment] 2019-12-05 09:57
@paulfalgout I concur, this looks like something else going on in your app, @Nadya913.

I'll close this for now. If you do some investigation and find that it is a problem with the SDK, feel free to reopen.

**Closed by stevehobbsdev** 2019-12-05 09:57 UTC
