### ISSUE TITLE
Auth0 configuration errors should ideally throw immediately rather than needing to wait for timeout.

### ISSUE THREAD

**Issue by Hawxy** [auth0/auth0-spa-js#526] opened 2020-07-14 07:56 UTC
### Describe the problem

In a multi-tenanted environment where subdomains are used to identify tenants, it's very likely a user may mistype the subdomain for a tenant. When `checkSession` is called whilst on a subdomain that hasn't been added to Auth0's permitted web origins, the site will hang after getting a 400 error back from the authorize endpoint until the timeout has been reached.

This issue also leads to some inconsistent behavior. A 403 `unauthorized_client` error, say from a `Callback URL Mismatch` will redirect the user to Auth0's generic error page (or your own if one is set). Whilst a 400 `invalid_request` caused by a `tenant.product.xxxxx.com does not have a registered origin` error will just timeout and not tell me what the problem is.

### What was the expected behavior?

I'd like the ability to have `checkSession` throw immediately on an auth0-caused 400 and bubble a specific exception up to the caller so I can check it and redirect the user to an authorization error page. I already have a similar redirection in-place if a user manages to reach our Auth0 Rule with an invalid tenant, but this issue is hit before our Rule is activated. In a perfect world I would just wildcard the subdomain in the web origins and let the rule handle this whole thing but that's still unsupported for the time being.

**Comment by stevehobbsdev** [comment] 2020-07-30 09:11
Thanks for raising this @Hawxy, and apologies for the radio silence here.

We're mostly at the whim of what Auth0 Server returns to us here. I'm assuming here that you're not using refresh tokens here. When you call `checkSession`, we make a call to the `/authorize` endpoint using a hidden iframe in order to get your auth code, which we can then exchange for a token using a normal `fetch` call. Normally what happens is that the response we get from the server to the iframe is a web page with a piece of JavaScript that uses `postMessage` to return the auth code to the app.

The problem is with certain errors is that you get a standard HTML error page that does not have this `postMessage` call in it. Hence we rely on the timeout. So ultimately this is a server concern and I don't have a good technical reason as to why this happens - but I will go and find out and report back.

In the meantime, there are a couple of knobs you can tweak on the SDK that may help:

* Use refresh tokens - this means that your app will not rely on that hidden iframe call
* Set `authorizeTimeoutInSeconds` to a lower value (the default is 60 seconds) ([docs](https://auth0.github.io/auth0-spa-js/interfaces/auth0clientoptions.html#authorizetimeoutinseconds))

**Comment by stevehobbsdev** [comment] 2020-08-17 10:25
> I think the SPA examples should be updated to check for a combination of state and either code OR error in the URL before handling the callback, so other users don't run into this head scratcher scenario.

This is useful feedback, thank you.

> ..the query response mode that refresh tokens use doesn't suffer from the same web origin restrictions as before

Can you expand on this? When you say "query response mode", are you referring to OAuth 2.0's implicit grant, or are you simply referring to how refresh tokens do not rely on a session cookie?

I'll close this for now, but have taken feedback on board to be actioned.

**Closed by stevehobbsdev** 2020-08-17 10:25 UTC
Labels: bug report

**Comment by Hawxy** [comment] 2020-08-17 11:53
> Can you expand on this? When you say "query response mode", are you referring to OAuth 2.0's implicit grant, or are you simply referring to how refresh tokens do not rely on a session cookie?

You can safely me ignore me on that one. 

When I was writing that response out, I noticed that on initial page load (with an auth0 session existing) that with refresh tokens enabled, the authorize endpoint was hit with `response_type=query` (Authorization Code grant?) instead of `response_type=web_message`, thereby solving the long-running issue regarding web origins mentioned here: https://community.auth0.com/t/how-come-allowed-web-origins-does-not-allow-wildcards/9185

However I'm now aware that silent auth relies on that response type, and thus this isn't a complete solution to the problem.

At least in my scenario, having `response_type=query` guaranteed when a user loads a non-existent subdomain, so my rule gets hit and the user redirected away without having to wait for the web origins timeout is good enough for me.

Thanks for your time. One of auth0's professional services teams will be reviewing our architecture in the near future, so I'll be sure to get them to review our solution for this particular problem.
