### ISSUE TITLE
E2E Testing

### ISSUE THREAD

**Issue by Ali-Doustkani** [auth0/auth0-spa-js#229] opened 2019-09-30 08:19 UTC
### Problem
I have to visit `auth0.com/login` page in my e2e tests and that is not a good idea. That would be great if I could do the login behind the scenes and don't hit the real login page.

### Describe the ideal solution
I know auth0-spa-js is written to work with Authorization Code with PKCE but maybe if it does support some kind of functionality for test scenarios I can do the authorization with Password Grant in my test code and pass the results to auth0-spa-js in my app! 
I can pass the result via URL or setting a cookie. I read some sources of the project, and I'm not sure that is possible with the current design, because Cookies are not responsible for dealing with tokens and I'm not sure using URL is a good solution!

**Comment by luisrudge** [comment] 2019-09-30 13:31
duplicate of #210

**Closed by luisrudge** 2019-09-30 13:31 UTC
