### ISSUE TITLE
loginWithPopup from chrome extension instantly closes on enterprise MacBooks

### ISSUE THREAD

**Issue by LeifRoss** [auth0/auth0-spa-js#567] opened 2020-08-31 17:31 UTC
### Describe the problem

loginWithPopup from chrome extension pops up and then closes a second later on MacBooks enrolled in enterprise networks. It only happens in this one combination. However, if developer tools are opened by inspecting the extension, then the login popup starts working normally again until the browser has been restarted. It is however difficult extracting any useful information due to the nature of the bug.

### What was the expected behavior?

Login popup would open, allowing the user to enter credentials and sign into the application.

### Reproduction
- Have a mac enrolled in a enterprise organization (jamf or alternatives)
- Trigger auth0 using loginWithPopup from a chrome extension popup.
- The auth0 popup closes by itself before the user can input any data into the form.

Might be easier to reproduce by simply clicking the login button on the relevant application: [Chrome Extension](https://chrome.google.com/webstore/detail/emberly-web-clipper/gdepklgalpgnddjcmhfcbpnokpjfkjhj)

**Can the behavior be reproduced using the [SPA SDK Playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground)?** No

[Video demonstrating the issue](https://drive.google.com/file/d/1Jx8_3LPuxRKdRDm0jSdOWxARtJUAHJMc/view)

Due to the nature of how this bug is behaving it is very difficult to get any sort of logs or stack traces. Because of the bug stops happening when we try to inspect the application using the chrome devtools. The bug only happens on enterprise macs, I have not been able to reproduce on any other platform. However, for all I know, I am missing some vital piece of configuration these devices require. But I do not really know how to proceed from here. Figured this is the best place to ask.

If you guys are unable to reproduce, we are more than open to a screensharing session from one of the affected devices!

### Environment
- **Version of `auth0-spa-js` used:** 1.9.0 and 1.11.0
- **Which browsers have you tested in?** Chrome
- **Which framework are you using, if applicable (Angular, React, etc):** React
- **Other modules/plugins/libraries that might be involved:** It is triggered from a chrome extension (the extension default window/popup), popups are not blocked in chrome settings.

Thanks for making this awesome library !

**Comment by adamjmcgrath** [comment] 2020-09-02 13:19
Hi @LeifRoss - thanks for raising this

My Mac is enrolled with jamf and I'm not able to reproduce the issue using your extension: https://chrome.google.com/webstore/detail/emberly-web-clipper/gdepklgalpgnddjcmhfcbpnokpjfkjhj

The popup stays open for 60 secs which is the default set by https://auth0.github.io/auth0-spa-js/interfaces/auth0clientoptions.html#authorizetimeoutinseconds

Couple of suggestions to debug:

- Check that you're not overriding this timeout in some cases either with the [client config](https://auth0.github.io/auth0-spa-js/interfaces/auth0clientoptions.html#authorizetimeoutinseconds) or the `loginWithPopup` [method config](https://auth0.github.io/auth0-spa-js/interfaces/popupconfigoptions.html#timeoutinseconds)
- Build a version of the SDK and Chrome Extension with a `debugger` statement in https://github.com/auth0/auth0-spa-js/blob/master/src/utils.ts#L111 and https://github.com/auth0/auth0-spa-js/blob/master/src/utils.ts#L118

**Comment by LeifRoss** [comment] 2020-09-03 06:55
Hey, thank you so much for the feedback. Going to do some more testing and then come back!

**Comment by stevehobbsdev** [comment] 2020-10-07 15:08
Closing this for now; feel free to continue the conversation if there's anything more we can do to help.

**Closed by stevehobbsdev** 2020-10-07 15:08 UTC
Labels: bug report

**Comment by ronilitman** [comment] 2022-01-17 13:20
@stevehobbsdev This issue still exists for me

**Comment by nextlevel3** [comment] 2022-02-11 16:20
Did you find a resolution to this? We have the same issue on Mac.
