### ISSUE TITLE
localstorage cache location ignored if cookies exist

### ISSUE THREAD

**Issue by nirvdrum** [auth0/auth0-spa-js#394] opened 2020-03-26 17:22 UTC
### Description

Based on the resolution status to #388, I've switched to to using the local storage cache location in the 1.7.0 beta. If working with a completely new browser session, this approach works fine with both Privacy Badger and Brave's default settings. However, if the user had previously used the site, such that auth0.com cookies are available, it looks like the local storage cache is ineffective. I haven't traced the code to see what's really going on, but I end up in the same login loop I reported in #388.

The solution appears to be deleting all cookies and then logging in again. At that point, things work fine with Privacy Badger and Brave. But, that's not exactly the most user-friendly of options. It would be much nicer if this library could handle that situation.

### Reproduction

The reproduction starts with the same steps from #388, reproduced here:

Set up a new tenant in Auth0 using default settings for cookies. Set up a React app using _auth0-spa-js_ and add something like the following (simplified for brevity):

```js
const { isAuthenticated, loading, loginWithRedirect } = useAuth0()

useEffect(() => {
  if (!loading && !isAuthenticated) {
      loginWithRedirect({})
  }
}, [isAuthenticated, loading, loginWithRedirect])
```

At this point, try to login using a browser with Privacy Badger installed with default settings (it will block the 3rd party auth0.com cookie) or use Brave with its default Shield setting. You'll end up in a login loop.

Now, update the `Auth0Provider` config by setting `cacheLocation="localstorage"`. Attempt to log in with the same browser session that was in a loop. See it remains in a loop. Close the tab, come back, same thing. Drop into your developer tools and clear out all cookies, then refresh the page, now you'll be able to log in successfully.

### Environment

> Please provide the following:

- **Version of this library used:** 1.7.0-beta.4
- **Version of the platform or framework used, if applicable:** React 16.12.0
- **Other relevant versions (language, server software, OS, browser):** Brave, Firefox or Chrome + Privacy Badger

**Comment by stevehobbsdev** [comment] 2020-03-31 19:59
@nirvdrum Can you supply us with a small repro to demonstrate the issue, or point us to some code? Just so we're on the same page when trying to fix it.

**Comment by nirvdrum** [comment] 2020-03-31 21:14
It's hard to just point you at code because you need to run it in one state to generate cookies, then change the cache location to local storage and then run it again with the cookies from the previous phase in place. I guess I could do it with two branches, but you'd still need to deploy them somewhere. As far as I know, the 3rd party cookie restriction with Privacy Badger isn't enforced from localhost.

**Comment by stevehobbsdev** [comment] 2020-03-31 21:35
I will try this as well, but it might be worth seeing if you can reproducing this using the playground built into the SDK itself.

* Clone the repo and check out the beta release tag (`git checkout v1.7.0-beta.4`)
* Run an `npm install`
* Start the playground using `npm start` and open http://localhost:3000

The playground allows you to do the full login flow and easily switch between memory and local storage - this should enable us to come up with some repro steps.

Let me know if that would help us get to the bottom of this.

**Comment by stevehobbsdev** [comment] 2020-04-24 09:28
@nirvdrum How are you getting on with testing the above? I'm afraid I cannot reproduce what you're seeing with the playground. It could be something to do with how the React app is configured.

Closing this for now but feel free to continue the discussion.

**Closed by stevehobbsdev** 2020-04-24 09:28 UTC
Labels: needs investigation
