### ISSUE TITLE
auth0-spa-js.production.legacy.js default export is undefined

### ISSUE THREAD

**Issue by Jorgevillada** [auth0/auth0-spa-js#83] opened 2019-07-17 13:12 UTC
hi,  Currently I have some problems with the transpilation of auth0-spa-js.production.js

```
Failed to compile.
Failed to minify the code from this file: 
 	./node_modules/@auth0/auth0-spa-js/dist/auth0-spa-js.production.js:1:12440 
Read more here: http://bit.ly/2tRViJ9
error Command failed with exit code 1.
```
I tried to use the build `auth0-spa-js.production.legacy.js`, but it fails
```javascript
import createAuth0Client from "@auth0/auth0-spa-js"; 

 const auth0FromHook = await createAuth0Client(initOptions);
```
webpack alias:
```
'@auth0/auth0-spa-js': node_modules/@auth0/auth0-spa-js/dist/auth0-spa-js.production.legacy.js
```

![image](https://user-images.githubusercontent.com/8599697/61377436-d2e81100-a868-11e9-8b47-f1b25773c497.png)

![image](https://user-images.githubusercontent.com/8599697/61377331-9ae0ce00-a868-11e9-9179-6a05595c2a39.png)

looking for the function getTokenSilently in auth0-spa-js.production.js exists, but in auth0-spa-js.production.legacy.js it does not exist

```
 "@auth0/auth0-spa-js": "^1.0.2",
```

**Comment by luisrudge** [comment] 2019-07-17 15:52
@Jorgevillada are you using angular?

**Comment by Jorgevillada** [comment] 2019-07-17 16:06
reactjs with webpack.

**Comment by luisrudge** [comment] 2019-07-17 16:31
Duplicate of https://github.com/auth0/auth0-spa-js/issues/57. Looks like an internal config issue. You should probably exclude our library from being transpiled

**Closed by luisrudge** 2019-07-17 16:31 UTC
