### ISSUE TITLE
User without Organization Membership caused infitine login redirect loop

### ISSUE THREAD

**Issue by areindl** [auth0/auth0-spa-js#1193] opened 2023-11-08 15:32 UTC
### Checklist

- [X] The issue can be reproduced in the [auth0-spa-js sample app](https://github.com/auth0-samples/auth0-javascript-samples/tree/master/01-Login) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-spa-js#readme), [Examples](https://github.com/auth0/auth0-spa-js/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-spa-js/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://auth0.com/docs/libraries/auth0-single-page-app-sdk) and [API documentation](https://auth0.github.io/auth0-spa-js/), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-spa-js/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

In our application, we have configured our Auth0 app such that it requires members to be part of an organization.

<img width="1148" alt="image" src="https://github.com/auth0/auth0-spa-js/assets/5536491/0f081472-2edc-4b68-9b98-4fcfe0ed1d1f">

While testing our application, we also had one test case for a user that does not belong to an organization. At the moment, this error is not properly communicated by auth0-spa-js.

Auth0 redirects back to use with this error message as part of the query:
![image](https://github.com/auth0/auth0-spa-js/assets/5536491/6d337e69-e421-4c36-9f78-6d73367e9188)

The problem occurs in a function getToken() that we use to get a valid token before we perform a backend request:

```js

        async getToken() {
            try {
                const token = await this.$auth0.getAccessTokenSilently()
                return token
            } catch (e) {
                console.log('getTokenError', e)
                await this.$auth0.loginWithRedirect()
            }
        },
        
```

The catched error message does only say "Login required":

<img width="529" alt="image" src="https://github.com/auth0/auth0-spa-js/assets/5536491/30b2f475-3d23-4b1e-879d-555c0b88d279">

### Expectation:

We would expect a more specific error message so we are able to handle the error better. For example: "Client requires organization membership"

### Reproduction

1. Make organization mandatory in Auth0
2. Login with user without org
3. Get a token
4. Check error message

### Additional context

We use @auth0/auth0-vue: 2.3.1

### auth0-spa-js version

2.1.2

### Which framework are you using (React, Angular, Vue...)?

Vue

### Framework version

3.3.2

### Which browsers have you tested in?

Chrome

**Comment by frederikprijck** [comment] 2023-11-08 15:36
Thanks for reaching out. Can you elaborate how the error in the URL relates to the `getTokenSilently` call?

When you use getTokenSilently, there is no visible URL that will represent the error or error_description.

Is the error in the URL perhaps coming from calling `loginWithRedirect`? If so, what error gets populated to Vue's `error` state as per https://github.com/auth0/auth0-vue/blob/main/EXAMPLES.md#error-handling ?

**Comment by frederikprijck** [comment] 2023-11-13 08:19
I gave this a try and am unable to reproduce this. When configuring Auth0 as  you mention, then using the [Vue sample app](https://github.com/auth0-samples/auth0-vue-samples), I get the following when trying to login:

![image](https://github.com/auth0/auth0-spa-js/assets/2146903/dacf0cf3-c68a-45cb-a80e-7a0a6e28243f)

As you can see, the error from the URL is properly populated to the `error` state property and visualized to the user accordingly.
In this case, you should not call `getAccessTokenSIlently`, because that makes no sense to do when the user is not authenticated in the first place.

However, for the sake or reproducing this I tried, and even that gave me the exact same error, visualized in the exact same way through the `error` state property.

Note, to be able to test the above I had to configure the playground to allow to request tokens when not logged in.

Closing this, as I can not reproduce this but happy to try and assist where needed. If you need further assistance, can you please try and reproduce using our playground?

```
git clone org-18199888@github.com:auth0-samples/auth0-vue-samples.git
cd 01-Login
npm i
npm run serve
```

Also be sure to rename `01-Login/auth_config.json.example` to `01-Login/auth_config.json` and replace the Domain and Client ID.

**Closed by frederikprijck** 2023-11-13 08:19 UTC
Labels: bug
