### ISSUE TITLE
Token refresh does not work in `auth0-spa-js`

### ISSUE THREAD

**Issue by sc-ivankorshun** [auth0/auth0-spa-js#931] opened 2022-07-18 12:52 UTC
### Describe the problem

The `auth0-spa-js` can be configured to refresh tokens (`useRefreshTokens` flag).
When an access token is expired `getTokenSilently()` tries to refresh it automatically.
But `getTokenSilently()` does not pass scope to the `/token` endpoint.
As a result, an ID token is not returned back and the “`ID token is required but missing`” error is thrown.

### Reproduction

1. Create a SPA with an automatic token refresh (`useRefreshTokens`) as explained in the Getting Started section:
[@auth0/auth0-spa-js - npm](https://www.npmjs.com/package/@auth0/auth0-spa-js)
2. Decrease lifetime of ID or access token to 70 seconds on https://manage.auth0.com/.
3. Open SPA and wait for 11 seconds (till the token is expired).
4. Call `getTokenSilently()` function.

**Actual result**: The “`ID token is required but missing`” error is thrown.
**Expected result:** The tokes are refreshed.

### Environment

- Version of `auth0-spa-js` used: `https://cdn.auth0.com/js/auth0-spa-js/1.22/auth0-spa-js.production.js`
- Which browsers have you tested in? Chrome.
- Which framework are you using, if applicable (Angular, React, etc): reproduced on both pure `auth0-spa-js` and React.
- Other modules/plugins/libraries that might be involved: no.

**Comment by stevehobbsdev** [comment] 2022-07-18 15:32
👋🏻  @sc-ivankorshun 

It's not necessary to pass a scope to `/oauth/token` as the refresh token is bound to the audience and scopes from when the user authenticated to get the refresh token in the first place.

I'm not sure why an ID token is not being returned to you - are you able to supply a HAR file for us to look at?

**Comment by sc-ivankorshun** [comment] 2022-07-19 07:20
Hi @stevehobbsdev,

You are right. One step is missing in the reproducible scenario.
It starts to fail with a custom rule that extends access token scope as described here:
https://auth0.com/docs/get-started/authentication-and-authorization-flow/call-your-api-using-the-authorization-code-flow#customize-tokens

Here is a simplified rule code to reproduce:
```
async function addSomeScope(user, context, callback) {
    context.request = context.request || {};
    context.request.query = context.request.query || {};
    context.request.body = context.request.body || {};
    context.accessToken = context.accessToken || {};

    var scope = context.accessToken.scope || context.request.query.scope || context.request.body.scope || '';

    context.accessToken.scope = scope.split(' ').concat(['my.scope.value']);

    return callback(null, user, context);
}
```

Here are network HAR and console log:
[token-refresh.zip](https://github.com/auth0/auth0-spa-js/files/9138504/token-refresh.zip)

**Comment by stevehobbsdev** [comment] 2022-08-05 16:11
Thanks for your patience here @sc-ivankorshun, I've had a play and I think I know what's going on.

1) First thing is that when setting `context.accessToken.scope`, this needs to be set to a string value, not an array of scopes. So something like `context.accessToken.scope = scope.split(' ').concat(['my.scope.value']).join(' ');` will fix that

2) Second thing is that when you're calling `/oauth/token`, your rule will only have access to the scopes that have been sent as part of that request - not the original scopes that were used when the user first authenticated. I suspect that you're getting a `ID token is required but missing` error is because the `openid` scope is not being included when you reconfigure the scopes. The `openid` scope is required for you to receive an ID token in the response, and I suppose because you're electing to override the access token scopes, Auth0 no longer considers the original scopes when returning the response. Something like the following should fix that (I've tried this in my own testing and appears to fix the issue:

```
context.accessToken.scope = scope.split(' ').concat(['my.scope.value']).join(' ');

if (!context.accessToken.scope.includes('openid')) {
 context.accessToken.scope = 'openid ' + context.accessToken.scope;
}
```

Let me know if that helps!

**Comment by sc-ivankorshun** [comment] 2022-08-08 06:29
Hi @stevehobbsdev,
1. Both array and string assigned to `context.accessToken.scope` lead to the same result.
Our production code sets it as a string. I have tried an array in the reproducible scenario to follow the official Auth0 example.
But the result is the same.

2. The `openid` scope value is used by a client to signal whether it needs an ID token. Hardcoding the `openid` scope value inside the rule forces an ID token to always be returned back.
Not all our clients are SPA based. We have backend-baed web applications as well as CLI applications. Some of our clients do not need an ID token.

**Comment by stevehobbsdev** [comment] 2022-08-08 10:26
For the `openid` case, I think you have two options:

1. See if it's possible that your non-SPA clients can just ignore the ID token when parsing the response
2. You're able to discriminate on the client ID inside your rule - `context.clientID` has the client being used, so you're able to check based on the client ID whether the `openid` scope should be included or not.

The SDK today _requires_ an ID token to be included in the response and is intended behaviour. I'll close this for now as I don't see this as an issue with this specific SDK, but happy to continue the conversation if you need further help.

**Closed by stevehobbsdev** 2022-08-08 10:26 UTC
Labels: bug report
