### ISSUE TITLE
User email_verified type as boolean but returned value is a string

### ISSUE THREAD

**Issue by klaascuvelier** [auth0/auth0-spa-js#833] opened 2021-11-06 13:53 UTC
### Describe the problem
The type for the `email_verified` property on the `User` class is typed as a `boolean` but the actual returned value on the `user$` object of the `AuthService` in the `@auth0/auth0-angular` package is a `string` (see included screenshot)
https://github.com/auth0/auth0-spa-js/blob/3ec6763f48a9a15b07962ef80abbc0dd3ca67c30/src/global.ts#L571

<img width="606" alt="Screenshot 2021-11-06 at 14 39 48" src="https://user-images.githubusercontent.com/354147/140611947-3ff52d33-e2d9-49a3-8565-5e36143d4b95.png">

I assume this issues applies to other SPA packages that use this library as well.

I also noticed an `email_verified` property on the `IdToken` interface as well. It is also typed as a boolean, not sure if the backend actually returns a `string` or `boolean`.

### What was the expected behavior?

Either the type should be `"true" | "false"` or `string`, or the returned value should be casted to a `boolean` 

### Reproduction

n/a

### Environment

- **Version of `auth0-spa-js` used:**
  - `@auth0/auth0-angular: 1.8.0` 
  - `@auth0/auth0-spa-js: 1.19.2`
- **Which browsers have you tested in?**
  - n/a
- **Which framework are you using, if applicable (Angular, React, etc):**
  - Angular
- **Other modules/plugins/libraries that might be involved:**
  - n/a

**Comment by frederikprijck** [comment] 2021-11-08 08:12
Hi @klaascuvelier,

Could you give us a better understanding of where you are seeing this exactly?

I looked into this by using our SDK's playground app:

- git clone this SDK repo
- npm install
- npm start
- click login with redirect
- click login redirect callback

This is what I get:

![image](https://user-images.githubusercontent.com/2146903/140705578-1caef6db-e789-4177-b53b-88115681cc11.png)

I also logged the response of `getUser`:

```
_self.auth0.getUser().then(function (user) {
     console.log({ user });
     _self.profile = user;
});
```
which gives me this:
![image](https://user-images.githubusercontent.com/2146903/140705709-f01be72f-532a-4102-9956-7e2caa5079bd.png)

On top of that, I also parsed the ID Token using jwt.io, where it is also a boolean:

![image](https://user-images.githubusercontent.com/2146903/140705916-70c9fb19-6ea8-40ee-bf21-dd0f9836fcde.png)

Last but not least, I tested the same thing in our Angular playground, where it also shows up as a boolean:

![image](https://user-images.githubusercontent.com/2146903/140706347-7e2f5553-e5bb-4a29-86b2-71ecc8f23976.png)

So I believe that having it typed as a boolean is correct, but it could be helpful to understand what is causing it to be a string in your case.

**Comment by klaascuvelier** [comment] 2021-11-08 09:14
Hey @frederikprijck, thanks for looking into this so quickly.
The issue for me occurs using the angular sdk, not sure if that changes anything (I would expect not). 

I tried setting up a quick [reproduction app in stackblitz](https://twitter.com/klaascuvelier/status/1457626236814073859) but ngcc failed so I created [this small repo on Github](insteadhttps://github.com/klaascuvelier/repro-auth0-type)
(`clientId` and `domain` not filled in in [app.module.ts](https://github.com/klaascuvelier/repro-auth0-type/blob/main/apps/repro-auth0-type/src/app/app.module.ts))
Hope this can help you identify the issue.

**Comment by frederikprijck** [comment] 2021-11-08 09:28
Hey @klaascuvelier ,

Running your sample app also shows a boolean for me... Do you have any rules set or any other tenant configuration that could be important for the reproduction?

![image](https://user-images.githubusercontent.com/2146903/140717113-bca7798a-7ec5-4766-91f8-6df4f488aada.png)

**Comment by klaascuvelier** [comment] 2021-11-08 09:36
I am using the Apple login, currently with the Auth0 test credentials.
I quickly checked and when I manually decode the token result the `email_verified` property there is also a string. 
Maybe something wrong/different with the Apple login code in the backend?

**Comment by frederikprijck** [comment] 2021-11-08 09:40
Thanks for checking, will have a conversation internally to see if this should be reflected in the types or to be considered an issue with the Apple integration.

**Comment by frederikprijck** [comment] 2021-11-08 09:57
Sharing here for reference, but it looks like this is how apple implemented their `email_verified` field: https://developer.apple.com/forums/thread/121411

**Comment by frederikprijck** [comment] 2022-01-14 14:53
I have raised this to the appropriate team internally, there isn't much we can do from the SDK perspective.
If this gets resolved, it should be correctly returning a boolean and no action from our SDK neither.

Closing this, but thank you for raising!

**Closed by frederikprijck** 2022-01-14 14:53 UTC
Labels: needs investigation, bug report

**Comment by klaascuvelier** [comment] 2022-01-14 15:02
I understand, thanks for keeping me up to date.
I'll work around it for now :)
