### ISSUE TITLE
Twitter Popup-auth is failing with Error: Popup closed at utils.ts:105:1 if user is not already signed in

### ISSUE THREAD

**Issue by dannnnthemannnn** [auth0/auth0-spa-js#1069] opened 2023-01-28 00:04 UTC
### Describe the problem

If you do loginwithpopup and use twitter, if the user is not already signed in to twitter and you click "login" it redirects to twitter.com in the popup window and issues an error to the caller that "Popup closed". 

### What was the expected behavior?

Prompt the user to sign in.

### Reproduction

Yes it is reproduced consistently. 

Step 1:
Log out of twitter.com

Step 2: 
Login using loginwithpopup and "twitter" connection type.

Step 3:
See an exception be thrown for "popup closed" even though the popup has not been closed and the login flow is still happening.

Step 4:
After you complete the rest of the flow get a hwite screen with this error:
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://localhost:3000') does not match the recipient window's origin ('https://dev-12345.us.auth0.com').

(replaced the auth0 dev route that was my own)

**Can the behavior be reproduced using the [SPA SDK Playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground)?**

No I didnt see a way to specify login with twitter

### Environment

- **Version of `auth0-spa-js` used:**
- 2.0.2
- **Which browsers have you tested in?**
- Chrome
- **Which framework are you using, if applicable (Angular, React, etc):**
- React
- **Other modules/plugins/libraries that might be involved:**

**Comment by frederikprijck** [comment] 2023-01-30 09:28
Thanks,

> No I didnt see a way to specify login with twitter

Twitter is enabled on the Auth0 level.  it will then work fine in the playground. 
I tried this in the playground, and it works as expected.

Uploading Auth0 - 30 January 2023.mp4…

Please try reproducing it in our playground and let us know what configuration causes the issue so we can determine hot to help you solve it,

**Comment by dannnnthemannnn** [comment] 2023-01-30 15:43
Here is a video of it reproducing in the sample app:
https://drive.google.com/file/d/17UBcoiC_rTz0ijbfXprvWCgCRTrxW7Sz/view?usp=sharing

I think the difference is that you need to be logged out of twitter @ twitter.com when starting the login flow to reproduce.

**Comment by frederikprijck** [comment] 2023-01-31 07:56
Thank you for sharing that, I was able to reproduce it.

I am unsure this has something to do with our SDK, but let me see internally what could be causing that.

Thanks.

**Comment by dannnnthemannnn** [comment] 2023-01-31 08:06
Glad to hear its reproducable! For what its worth, we explored around to find other apps that use twitter popup auth when trying to figure out why it was happening and one such site that appears to use firebase auth seemed to not have this problem. (Example: https://www.trycaravan.com/)

**Comment by frederikprijck** [comment] 2023-01-31 08:23
Are you using developer keys, or have u entered your own application keys in the Auth0 dashboard for the twitter connection?

**Comment by frederikprijck** [comment] 2023-01-31 11:29
We looked into this, and it appears the issue also exist with firebase: https://github.com/firebase/firebase-js-sdk/issues/6910

As mentioned in the thread, the issue does not exist for everyone / all the time. But they do experience the exact same behavior.

In general, we encourage people to use `loginWithRedirect` instead of popup anyway, so I would recommend the same here as I believe it's twitter that's closing the popup resulting in behavior like we are seeing in several SDKs, including Firebase and Auth0.

Because of the fact that twitter is closing the popup, and opening another, we can not distinguish between a user closing the popup, and twitter closing it.

**Comment by frederikprijck** [comment] 2023-02-09 07:54
As I do not believe there is much we can action from our SDK, I am going to close this issue.

**Closed by frederikprijck** 2023-02-09 07:54 UTC
Labels: bug
