### ISSUE TITLE
Cannot find name: AbortSignal

### ISSUE THREAD

**Issue by Benzer1406** [auth0/auth0-spa-js#763] opened 2021-07-09 00:12 UTC
I think there is a bug introduced since version 1.16.1 at least for TypeScript: 
![image](https://user-images.githubusercontent.com/33852084/125005050-cb5b3d00-e028-11eb-927d-a31c56809ab9.png)

**Comment by stevehobbsdev** [comment] 2021-07-09 07:21
🤔 can you confirm that it works previous to 1.16.1? Which browser are you seeing this in?

**Comment by stevehobbsdev** [comment] 2021-07-22 11:52
I'm unable to reproduce this so far but if you have any more details that might help, please let me know.

This could also be environmental - are you using it within a TypeScript project that [does not specify the `dom` library](https://stackoverflow.com/questions/59859347/abortcontroller-missing-in-typescript)?

**Comment by stevehobbsdev** [comment] 2021-08-04 13:05
Closing this for now, but if you're still having trouble, please feel free to continue the conversation.

**Closed by stevehobbsdev** 2021-08-04 13:05 UTC
Labels: bug report, cannot repro, more info needed
