### ISSUE TITLE
createAuth0Client timeout gives undesirable offline behaviour

### ISSUE THREAD

**Issue by sampsonjoliver** [auth0/auth0-spa-js#292] opened 2019-11-29 11:57 UTC
### Description

Similar to https://github.com/auth0/auth0-spa-js/issues/37 there is a 60-second timeout in the `runIframe` method inside `checkTokenSilently` which is called during `createAuth0Client`.

Currently, when calling `createAuth0Client`, the `checkTokenSilently` call will block the return of the created auth0 instance until completion, which, depending on network speed, will block the app for up to 60 seconds before the application can even acquire the auth0 interface.

This is especially undesirable for an offline-capable PWA, as the timeout will run for the full 60 seconds _and then_ will yield the interface. It seems far more intuitive to immediately return the interface, asynchronously invoke a memoized silent token refresh, and allow the app to attempt to acquire the latest auth state by invoking `isAuthenticated` -- and _this_ may run for up to 60 seconds.

### Reproduction

1. Follow https://auth0.com/docs/quickstart/spa/react/01-login for a fresh CRA with service-workers enabled
2. While online, perform a login
3. Disconnect the device from wifi/data and refresh the page

### Environment

- **Version of this library used:**
1.6.0
- **Version of the platform or framework used, if applicable:**
create-react-app, react@16.11
- **Other relevant versions (language, server software, OS, browser):**
Chrome 78

**Comment by stevehobbsdev** [comment] 2019-12-02 08:53
@sampsonjoliver Not sure I follow. `createAuth0Client` just returns a Promise - couldn't you retrieve the promise instance and then handle `then` or `catch`, which will be invoked once the promise completes?

**Comment by sampsonjoliver** [comment] 2019-12-02 23:00
@stevehobbsdev  I can - but the promise will take a full 60 seconds to resolve because it's awaiting the silent token refresh. Which means my application is waiting for this whole time, just to get an instance of the auth client.

See my annotations in the `createAuth0Client` method below

```javascript
export default async function createAuth0Client(options: Auth0ClientOptions) {
  validateCrypto();

  const auth0 = new Auth0Client(options);

  if (!ClientStorage.get('auth0.is.authenticated')) {
    return auth0;
  }
  try {
    // 1. When the client is offline or has limited network connectivity, this call will take 60 seconds to reject. This is due to the timeout in `checkTokenSilently ->runIframe`
    await auth0.getTokenSilently({
      audience: options.audience,
      scope: options.scope,
      ignoreCache: true
    });
  } catch (error) {
    // 2. Then after a minute has passed and checkTokenSilently has rejected, this catch block will run
  }
  // 3. And only now is the auth0 client returned
  return auth0;
}
```

So my application, when consuming this method, runs like below:
```javascript
const app = () => <AuthProvider><App /></AuthProvider/>

const Auth0Context = React.createContext()

const AuthProvider = () => {
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    const auth0Client = await createAuth0Client( ... )

    // ... 60 seconds elapses ...
    
    const isAuthenticated = await auth0Client.isAuthenticated();
    setIsAuthenticated(isAuthenticated);

    if (isAuthenticated) {
      const user = await auth0Client.getActiveUser();
      setUser(user);
    }
    setLoading(false);
  }, []);

  return <Auth0Context.Provider vaue={{loading, auth0Client}}>
    {children}
  </Auth0Context.Provider>
}
```

Hence, my app will not be able to resolve the user's auth state, or even acquire an instance of the auth0Client, for a whole minute.

**Comment by stevehobbsdev** [comment] 2019-12-03 10:43
Gotcha. So it's blocking in the sense that your app needs to wait for the operation to be done.

Can you just check something - this should not be taking the full 60 seconds in any case, it should be a quick round-trip to the auth server. Could you check the response from the server using the network tab? We've seen this timeout issue happen before when there's a configuration problem, usually because the **Allowed Web Origins** setting hasn't been configured in your Auth0 app.

Also see [this FAQ question](https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-does-the-auth0client-object-take-a-long-time-to-initialize) for more detail.

Let me know how you get on. As an aside, we do want to make the timeout configurable as the default of 60 seconds is way too long, but most of the time it's because of configuration ☝️

**Comment by sampsonjoliver** [comment] 2019-12-03 22:25
I'm not sure if I'm not explaining myself well here or not. Probably you just get a lot of issues that are to do with configuration issues haha, but this isn't one of them I promise you.

I am talking about the case where my application is *offline*. There is no internet, so there can be no round-trip to the server.

I know my application is configured correctly, because everything works _perfectly fine_ when the application is *online*. But I want to make a PWA SPA that can also run *offline*, with no connectivity, and so the round-trip to the auth server will *always timeout*.

**Comment by stszap** [comment] 2019-12-04 08:24
Please excuse me for butting in but why should it be stuck for 60 seconds even if there is a configuration error? Shouldn't the promise just error immediately when Auth0 return _anything_? Why does it have to wait that long?

**Comment by sampsonjoliver** [comment] 2019-12-04 09:11
Heh, also a good question.

Regarding [that FAQ question](https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-does-the-auth0client-object-take-a-long-time-to-initialize), I'm a bit stumped as to why the design decision was made for this API to *have* to initialise by communicating with the auth server. Why do that round-trip on create, rather than on the first call to any of the `getUser`/`isAuthenticated` methods?

**Comment by stevehobbsdev** [comment] 2019-12-04 10:05
Right, I understand now. I missed the part in your original message about this being offline. I know you alluded to it as an example but it wasn't clear that this is core to your scenario.

So during initialization, there is a call to `getTokenSilently` which is used to refresh the user's session. If they're already logged in to Auth0, we can refresh their local authenticated state as a convenience (although, it's obviously not a convenience in this scenario). The way `getTokenSilently` works is that it uses an iframe to call the `/authorize` endpoint, setting the response mode to `web_message`. In order to receive the tokens from the server, it listens for the message event being fired from the iframe.

Now, if you're offline you're probably getting stuck because you never contact the server and so the event never fires, hence hitting the timeout.

@stszap In your case, depending on the error that Auth0 server generates, it may not fire that message event either, hence hitting the timeout in that case too.

@sampsonjoliver What would be a preferred solution for your case? Would it be enough to put in a configurable timeout? I'm also keen to learn about how your application will behave when it's offline; would your users just always be unauthenticated until they regain network connectivity?

**Comment by sampsonjoliver** [comment] 2019-12-04 12:32
@stevehobbsdev yep, that's it!

For my company's app, just to give an example, what we do is essentially wrap that auth0-js or react-native-auth0 clients with an interface that will store any successful login response's token in to AsyncStorage. Then, when the client is online, any effort to read the token will either return the cached token if it is still valid, or else refresh it if it is expired. If the refresh fails due to "real" reasons, such as a `login_required` error, then that error is propagated upward and the app handles it by showing a relevant error, and redirecting the user to a login page.

However, if the client is _offline_ when it asks the interface for a token, or if connectivity is poor and the refresh attempt times out, the interface just returns the last-saved expired token and an `expired: true` property, with no thrown error. Because our backend services will check for any expired JWTs in their request headers and reject based on this, this is safe for our purposes -- and if the app is truly offline, it shouldn't be able to make any network requests anyway. So this is treated as a sort of "suspended" auth state -- the user can interact with locally-cached data (e.g. data cached by a service worker) without being kicked out of the app, but once they come back online, a refresh token attempt must succeed before they can query any backend services.

---

Discussing *this* library, I know that this lib uses some measure of local caching, such as the `auth0.is.authenticated` key.  I think what could work best would be:
1) allowing some bypass so that an app can get an instance of the auth0Client without *requiring* a successful `getTokenSilently` call to first succeed` 
```typescript
if (!ClientStorage.get('auth0.is.authenticated') || params.skipSilentCheck) {
    return auth0;
  }
```
2) Exposing the `auth0.is.authenticated` key through some method like `hasExistingLogin()`, or else getting the last-acquired jwt from Cookies (I believe it is currently reading from in-memory cache?) and returning that through the `isAuthenticated` and `getUser` methods
```
  public async getUser(
    options: GetUserOptions = { ... }
  ) {
    options.scope = getUniqueScopes(this.DEFAULT_SCOPE, options.scope);
    ...
    return storage.get('token').decodedToken.user || cache.decodedToken.user
  }
```

This would probably also require being able to customise the cookie expiry policy to be longer than 1 day, but essentially this would provide bypasses so an app can get the user's last-known auth state, without requiring a silent refresh, and puts the control into the application logic to manage manually calling `getTokenSilently` when a new, valid token is required.

**Comment by vitorbaptista** [comment] 2020-01-04 16:38
I'm facing a similar issue, although caused by slow Internet connectivity (not being offline). With this silent querytto `getTokenSilently`, my app's login page flow is:

1. User enters into Login page
1. We call `useAuth0()` and wait for `loading` to be false
  * In my tests, this can take up to 45 seconds. This is before we even redirect the user to the Auth0 login page
1. The user logs in and is redirected back to my app
1. We call `useAuth0()` again to be able to handle the callback and get the user data
  * Another ~45 seconds pass
1. Only then we're able to get the user details

As you can imagine, this is a painful experience.

**Comment by stevehobbsdev** [comment] 2020-01-06 11:13
@vitorbaptista and the times you're seeing are purely down to the slow internet connectivity? i.e. otherwise, the transactions between your app and Auth0 all happen successfully. Bear in mind that while Auth0 will return `200` response codes, it may return an error description within the body for calls to `/authorize`, so they're worth inspecting to make sure.

**Comment by stevehobbsdev** [comment] 2020-03-17 13:30
👋 Today we merged a new addition #377 which allows you to directly access the Auth0Client constructor instead of making you use the factory function. This way you can effectively bypass the getTokenSilently call on startup. This means at some point you will have to manually call getTokenSilently to refresh your session.

Closing this for now but if that does not allow you to solve your issue, please feel free to continue the conversation.

**Closed by stevehobbsdev** 2020-03-17 13:30 UTC

**Comment by sampsonjoliver** [comment] 2020-03-18 01:11
Fantastic! I'll try and give this a go in my project sometime shortly and let you know how it goes :)

**Comment by stevehobbsdev** [comment] 2020-03-26 15:46
@sampsonjoliver Just to circle back here, this feature was pulled from master but has just been released into the beta version. This can be installed using `auth0-spa-js@1.7.0-beta.5` if you still wanted to try it out.
