### ISSUE TITLE
Test fails when using j-toml package

### ISSUE THREAD

**Issue by weblaetitia** [auth0/auth0-spa-js#978] opened 2022-09-12 07:55 UTC
### Describe the problem

There is a conflict between auth0-spa-js and [j-toml](https://www.npmjs.com/package/@ltd/j-toml).

The `npm run test` command will display the error below:

```
    Failed to construct 'TextDecoder': the 'fatal' option is unsupported.

    > 1 | import TOML from "@ltd/j-toml";
        | ^
      2 |
      3 | const Toml = () => {
      4 |   const source = `

      at new n (node_modules/@auth0/auth0-react/node_modules/@auth0/auth0-spa-js/dist/auth0-spa-js.production.esm.js:15:38775)
      at node_modules/src/parse/.ts:18:34
      at node_modules/@ltd/j-toml/index.js:2:81
      at Object.<anonymous> (node_modules/@ltd/j-toml/index.js:5:3)
      at Object.<anonymous> (src/Toml.jsx:1:1)
      at Object.<anonymous> (src/App.tsx:4:1)
      at Object.<anonymous> (src/App.test.tsx:3:1)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)

```

### What was the expected behavior?

Test should pass

### Reproduction

Use `j-toml` and `auth0-spa-js` libraries with Jest test.

You can check this minimal app I've created on this repo: [https://github.com/weblaetitia/minimal-textdecoder-app](https://github.com/weblaetitia/minimal-textdecoder-app)
Run `npm run test`
   
### Environment

- React 18.2.0
- auth0-react 1.10.2
- j-toml 1.35.2
- auth0-spa-js 1.22.4

**Comment by frederikprijck** [comment] 2022-09-12 08:36
Thanks for reporting this.

TextEncoder/TextDecode is not supported in Jest, therefor it seems like the TOML package has some issues.
To solve this, configure TextEncoder and TextDecoder in setupTest.ts:

```

const { TextDecoder, TextEncoder } = require('util')

global.TextDecoder = TextDecoder;
global.TextEncoder = TextEncoder;
```

This should make the error go away, but replace it with another error:

>  Error: Uncaught [Error: For security reasons, `window.crypto` is required to run `auth0-spa-js`.]

This error is expected, as you can not run our SDK in an environment that does not support window.crypto, which does not exist in Jest.
Therefore, you will need to mock a couple of things, one way would be to use: 

```
jest.mock('@auth0/auth0-react', () => ({ Auth0Provider: ({ children }: any) => <div>{children}</div> }));
```

This is specific to React, as you are using our React SDK.
Once I make those changes, as well as fix the test it self to search for `I_am_normal` instead of `learn react`, the test succeeds:

![image](https://user-images.githubusercontent.com/2146903/189608965-b9fb7f6e-6ccc-4f38-8022-fedee00ef8f1.png)

For what it's worth, we use the same solution for running our own tests inside Auth0-SPA-JS on Jest: https://github.com/auth0/auth0-spa-js/blob/v2/jest.environment.js (we are using an environment instead of defining a global in. setupJest, but the end result is the same).

Closing as it looks like the issue is not in our SDK, but due to the lack of support of TextEncoder and TextDecoder in Jest-DOM, see: https://github.com/jsdom/jsdom/issues/2524.

**Closed by frederikprijck** 2022-09-12 08:36 UTC
Labels: bug report

**Comment by weblaetitia** [comment] 2022-09-12 09:19
Thank you for your quick response! I solved the issue with this workaround 
 [https://github.com/jsdom/jsdom/issues/2524#issuecomment-1108991178](https://github.com/jsdom/jsdom/issues/2524#issuecomment-1108991178)
