### ISSUE TITLE
auth0.getIdTokenClaims() returns claims as undefined in Firefox 103

### ISSUE THREAD

**Issue by elijah-martens** [auth0/auth0-spa-js#947] opened 2022-08-12 21:49 UTC
Describe the problem
auth0.getIdTokenClaims() returns claims as undefined in Firefox 103

What was the expected behavior?
in other browsers, auth0.getIdTokenClaims() returns a valid claims object

Reproduction
Step 1: await auth0.getTokenSilently(); 
Step 2: const claims = await auth0.getIdTokenClaims()
Step 3: claims is undefined. 

Version of auth0-spa-js used: 1.22.2
Which browsers have you tested in?  This issue only occurs in FireFox, I used version 103.0.2
Which framework are you using, if applicable (Angular, React, etc): React

**Comment by stevehobbsdev** [comment] 2022-08-17 11:04
Hi @elijah-martens,

I'm not able to reproduce this in Firefox 103. I've set up a quick test using the [built-in playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground) and got it to print out the results of `getIdTokenClaims()` after authentication, and I get a result back.

Check if you can reproduce this scenario using the playground. If you can't and you're still getting the issue, please point me to a small repro app and I'll happily take a look.


https://user-images.githubusercontent.com/766403/185101356-764e6cd9-8cc4-4f94-b5fd-abb939e38128.mov

**Comment by ewanharris** [comment] 2022-08-30 15:57
Hey @elijah-martens, are you still seeing this issue? If so, were you able to reproduce in the [playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground) or another minimal sample at all?

**Comment by vvilhonen** [comment] 2022-09-07 06:53
I'm having the same behaviour with react and version 1.22.3. I had cache and cacheLocation set to undefined. When setting cacheLocation to localStorage it works the same in firefox and chrome.

**Comment by frederikprijck** [comment] 2022-09-07 12:35
Closing this for now, happy to reopen if this is still an issue, but would be useful to provide a snippet or reproduction sample so we can see what's going on.

**Closed by frederikprijck** 2022-09-07 12:35 UTC
Labels: more info needed, bug report, cannot repro
